// ============================================================================
// MCP tool — get_readiness_report
// ============================================================================
//
// Returns an abbreviated 10D Intelligence Report for the authenticated user.
//
// PRIVACY/SECURITY DESIGN:
//   - userId + teamId come from getMcpContext() (JWT-verified); NEVER from args
//   - Output is a Zod-validated allowlist (Per-tool field allowlist defense)
//   - Strips internal IDs, raw analytics, AI prompts, and large nested blobs
//     that the LLM doesn't need (and shouldn't see for surface-area reasons)
//   - Reuses get6DReport via callController — same multi-tenancy filter
//     the web report uses (req.teamId)
//
// SCHEMA DESIGN:
//   We deliberately return a *summary* shape, not the full report. The
//   full report is ~100KB; the LLM doesn't need it. This shape captures
//   the 90% of "how am I doing?" answer in <5KB.
// ============================================================================

import { z } from "zod";
import { getMcpContext } from "../context.js";
import { callController } from "../utils/captureRes.js";
import { get6DReport } from "../../controllers/stats.controller.js";
import { wrapUserContent } from "../utils/safeOutput.js";

// ── Input schema ─────────────────────────────────────────────────────
const inputSchema = z
  .object({
    // include_basis: when true, surface the per-dim basis lines (deeper
    // diagnostic detail). Off by default to keep the response compact.
    include_basis: z.boolean().optional(),
  })
  .strict();

// ── Output schema (per-tool field allowlist) ────────────────────────
// Zod enforces: tool can only return these fields. Anything else → error.
// This is the multi-tenant + PII guard at the response layer.
const dimSchema = z.object({
  key: z.string(),
  status: z.enum(["active", "inactive"]),
  score: z.number().nullable(),
  n: z.number(),
  ci: z.tuple([z.number(), z.number()]).nullable(),
  basis: z.array(z.string()).optional(),
  activationMessage: z.string().optional(),
});

// ── Implementation ──────────────────────────────────────────────────
async function handler(args) {
  const { userId, teamId, globalRole, teamRole } = getMcpContext();
  if (!teamId) {
    return {
      content: [
        {
          type: "text",
          text: "No active team context. Switch to a team in the web UI before querying readiness.",
        },
      ],
      isError: true,
    };
  }

  // Reuse the existing controller. Same multi-tenancy filter, same v2
  // dim computations, same source of truth as the web report.
  const captured = await callController(get6DReport, {
    user: { id: userId, globalRole, currentTeamId: teamId, teamRole },
    teamId,
  });

  // The controller wraps everything in { success: true, data: { report } }.
  const report = captured?.data?.report;
  if (!report) {
    return {
      content: [{ type: "text", text: "Readiness report unavailable." }],
      isError: true,
    };
  }

  // Build the abbreviated shape — small enough for LLM context, rich
  // enough to answer "how am I doing".
  const includeBasis = args?.include_basis === true;
  const dimensions = (report.dimensions || []).map((d) => {
    const out = {
      key: d.key,
      status: d.status,
      score: d.score ?? null,
      n: d.n ?? 0,
      ci: Array.isArray(d.ci) && d.ci.length === 2 ? [d.ci[0], d.ci[1]] : null,
    };
    if (includeBasis && Array.isArray(d.basis)) {
      out.basis = d.basis;
    }
    if (d.status === "inactive" && d.activationMessage) {
      out.activationMessage = d.activationMessage;
    }
    return dimSchema.parse(out);
  });

  const overall = report.overall?.score ?? null;
  const overallCi =
    Array.isArray(report.overall?.ci) && report.overall.ci.length === 2
      ? [report.overall.ci[0], report.overall.ci[1]]
      : null;

  const tier = report.tier?.highest
    ? {
        ready: report.tier.highest.id,
        name: report.tier.highest.name,
        threshold: report.tier.highest.threshold,
      }
    : null;
  const nextTier = report.tier?.next
    ? {
        id: report.tier.next.id,
        name: report.tier.next.name,
        threshold: report.tier.next.threshold,
        gap: report.tier.next.overallGap,
      }
    : null;

  const summary = {
    overall_score: overall,
    overall_ci: overallCi,
    coverage: {
      active: report.reportCoverage?.active ?? 0,
      total: report.reportCoverage?.total ?? 6,
      pct: report.reportCoverage?.pct ?? 0,
    },
    tier_currently_ready: tier,
    next_tier: nextTier,
    dimensions,
    // Verdict prose is user-facing text generated by AI — wrap in user_*
    // tags as a defense in depth even though it's *our* AI output.
    verdict_headline: report.verdict?.headline
      ? wrapUserContent("verdict_headline", report.verdict.headline, { maxChars: 800 })
      : null,
  };

  return {
    content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
  };
}

// ── Registration ─────────────────────────────────────────────────────
export function register(server) {
  server.registerTool(
    "get_readiness_report",
    {
      title: "Get readiness report",
      description:
        "Get the authenticated user's 10D Intelligence Report summary — overall score, tier readiness, " +
        "and per-dimension scores (D1 Pattern Recognition, D2 Solution Depth, ..., D10 Verification " +
        "& Meta-cognition). Returns inactive dims with activation messages so the LLM can suggest " +
        "what to do to unlock them. Pass include_basis=true to surface per-dim basis lines for " +
        "deeper diagnostic detail.",
      inputSchema: inputSchema.shape,
    },
    handler,
  );
}
