-- True when the note was generated by the system (today: from an AI
-- Solution Review). UI uses it to distinguish auto-notes; the auto-note
-- pipeline uses it as the safety flag — user-edited notes never get
-- overwritten on re-analysis. Default false matches existing rows.

ALTER TABLE "notes" ADD COLUMN "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
